### ISSUE TITLE
Issue with 'Watch Round' button

### ISSUE THREAD

**Issue by rodent567** [bugdone/headshotbox#31]
I seem to be having an issue with the watch round button. CS starts but the demo doesnt. I think I know why.

My console reads:
Executing deferred playdemo: F:\Old
CDemoFile::Open: couldn't open file F:\Old.dem for reading.

The directory to my CSGO is F:\Old Windows\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive

It seems like the console isn't tolerating a space in the directory name.

Thanks.

**Comment by abenea** [comment]
What headshotbox and browser version are you using?

**Comment by rodent567** [comment]
I am using version 0.3.0 on the latest Chrome version

**Comment by abenea** [comment]
Please download the latest headshotbox version, this was fixed.

**Comment by rodent567** [comment]
Update: I have downloaded the latest version and the same issue persists.

**Comment by abenea** [comment]
Did you restart the application? This is done by closing the window started by the .bat file and running the .bat from the new version. I don't know for sure, but the browser cache might also be an issue.

If it still doesn't work, please right-click the watch button link, choose "Copy link address" and paste it here.
